var substringMatcher = function (strs) {
    return function findMatches(q, cb) {
        var matches, substringRegex;

        // an array that will be populated with substring matches
        matches = [];

        // regex used to determine if a string contains the substring `q`
        substrRegex = new RegExp(q, 'i');

        // iterate through the pool of strings and for any string that
        // contains the substring `q`, add it to the `matches` array
        $.each(strs, function (i, str) {
            if (substrRegex.test(str)) {
                matches.push(str);
            }
        });

        cb(matches);
    };
};

var states = [
    "Aboleth",
    "Angel, Deva",
    "Angel, Planetar",
    "Angel, Solar",
    "Animated Armor",
    "Ankheg",
    "Azer",
    "Basilisk",
    "Behir",
    "Black Pudding",
    "Bugbear",
    "Bulette",
    "Centaur",
    "Chimera",
    "Chuul",
    "Cloaker",
    "Cockatrice",
    "Darkmantle",
    "Demon, Balor",
    "Demon, Dretch",
    "Demon, Glabrezu",
    "Demon, Hezrou",
    "Demon, Marilith",
    "Demon, Nalfeshnee",
    "Demon, Quasit",
    "Demon, Vrock",
    "Devil, Barbed",
    "Devil, Bearded",
    "Devil, Bone",
    "Devil, Chain",
    "Devil, Erinyes",
    "Devil, Horned",
    "Devil, Ice",
    "Devil, Imp",
    "Devil, Lemure",
    "Devil, Pit Fiend",
    "Doppelganger",
    "Dragon Turtle",
    "Dragon, Black",
    "Dragon, Blue",
    "Dragon, Brass",
    "Dragon, Bronze",
    "Dragon, Copper",
    "Dragon, Gold",
    "Dragon, Green",
    "Dragon, Red",
    "Dragon, Silver",
    "Dragon, White",
    "Drider",
    "Dryad",
    "Duergar",
    "Elemental, Air",
    "Elemental, Earth",
    "Elemental, Fire",
    "Elemental, Water",
    "Elf, Drow",
    "Ettercap",
    "Ettin",
    "Flying Sword",
    "Gargoyle",
    "Gelatinous Cube",
    "Genie, Djinni",
    "Genie, Efreeti",
    "Ghast",
    "Ghost",
    "Ghoul",
    "Giant, Cloud",
    "Giant, Fire",
    "Giant, Frost",
    "Giant, Hill",
    "Giant, Stone",
    "Giant, Storm",
    "Gibbering Mouther",
    "Gnoll",
    "Gnome, Deep",
    "Goblin",
    "Golem, Clay",
    "Golem, Flesh",
    "Golem, Iron",
    "Golem, Stone",
    "Gorgon",
    "Gray Ooze",
    "Grick",
    "Griffon",
    "Grimlock",
    "Hag, Green",
    "Hag, Night",
    "Hag, Sea",
    "Half-Red Dragon Veteran",
    "Harpy",
    "Hell Hound",
    "Hippogriff",
    "Hobgoblin",
    "Homunculus",
    "Hydra",
    "Invisible Stalker",
    "Kobold",
    "Kraken",
    "Lamia",
    "Lich",
    "Lizardfolk",
    "Magmin",
    "Manticore",
    "Medusa",
    "Mephit, Dust",
    "Mephit, Ice",
    "Mephit, Magma",
    "Mephit, Steam",
    "Merfolk",
    "Merrow",
    "Mimic",
    "Minotaur",
    "Mummy",
    "Mummy Lord",
    "Naga, Guardian",
    "Naga, Spirit",
    "Nightmare",
    "Ochre Jelly",
    "Ogre",
    "Ogre Zombie",
    "Oni",
    "Orc",
    "Otyugh",
    "Owlbear",
    "Pegasus",
    "Plesiosaurus",
    "Pseudodragon",
    "Purple Worm",
    "Rakshasa",
    "Remorhaz",
    "Roc",
    "Roper",
    "Rug of Smothering",
    "Rust Monster",
    "Sahuagin",
    "Salamander",
    "Satyr",
    "Shadow",
    "Shambling Mound",
    "Shield Guardian",
    "Shrieker",
    "Skeleton",
    "Skeleton, Minotaur",
    "Skeleton, Warhorse",
    "Specter",
    "Sphinx, Androsphinx",
    "Sphinx, Gynosphinx",
    "Sprite",
    "Stirge",
    "Succubus/Incubus",
    "Tarrasque",
    "Treant",
    "Triceratops",
    "Troll",
    "Tyrannosaurus Rex",
    "Unicorn",
    "Vampire",
    "Vampire Spawn",
    "Violet Fungus",
    "Werebear",
    "Wereboar",
    "Wererat",
    "Weretiger",
    "Werewolf",
    "Wight",
    "Will-o’-Wisp",
    "Wraith",
    "Wyvern",
    "Xorn",
    "Zombie"
];

$('#tokenLabelInput').typeahead({
    hint: true,
    highlight: true,
    minLength: 3
},
    {
        name: 'monsters',
        source: substringMatcher(states)
    });